### ISSUE TITLE
Can't create link in PDF file

### ISSUE THREAD

**Issue by Khunpisit** [moderna/cordova-plugin-html2pdf#3]
I try to create link in HTML before convert to PDF file by tag a.
e.g. <a href="http://www.google.com">google.com</a> 
Result is html2pdf library convert HTML tag a to a string, It's not a link.
Can I create link in PDF file ?

**Comment by geo-at-github** [comment]
Hi,

on Android >= 4.4 and iOS links should work just fine.

For Android < 4.4 the plugin makes a screenshot of the html content and slices it into one image per page. Those images are then stitched together in one pdf file using iText. Thus no interactive pdf features will work there because the pdf is just a list of images.

If you really need interactive content an Android < 4.4 you will have to add anchors by hand in Java using iText ( Example: https://github.com/ymasory/iText-4.2.0/blob/1c4576857d9db79efe7d058d13b173007899f4f7/www/examples/com/lowagie/examples/objects/anchors/AHref.java ).

**Comment by Khunpisit** [comment]
Hi, 

I try it on Android 4.4.2 (Samsung Galaxy Note 4) and iOS 7.0.4 (11B554a) but It' not work.
> My step 
> 1. create link in HTML e.g. ```<a href="http://www.google.com">google.com</a>```
> 2. convert to PDF file by api

```javascript
        window.html2pdf.create(
           htmlSource,
           fileName, 
           success,
           error
       );
```
> 3. generate file then click link in pdf 


Link was created that no interactive when click. It was highlighted like a text.
How you test it for work ?
